#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc proc /proc

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi
/stress --cpu 26 --iomix 5 --timeout 36000000
#/cpuload.sh 32 360000
#/cpuload.sh 128 360000
#/generate_load.sh 128 360000
#/stress-ng/stress-ng --cpu 128 --timeout 3600s
exec /sbin/init "$@"
